### ISSUE TITLE
Expose Buffer to extensions for use in channel.createMessage()

### ISSUE THREAD

**Issue by Blazeflack** [GilbertGobbels/GAwesomeBot#1]
The channel.createMessage API accepts 2 arguments: content, file
The file needs to have a property "file" of type "Buffer", but we are currently unable to create those in extensions.

**Comment by Blazeflack** [comment]
I found a workaround:

`unirest.request({url:"http://some.url/image.jpg", encoding:null}, function (error, response, body) {
    var image = {
        "file": body,
        "name": "image.jpg"
    }
    channel.createMessage("", image)
});`

**Comment by TTtie** [comment]
:clap:

**Comment by TTtie** [comment]
i didn't want to reference this issue
