### ISSUE TITLE
[Issue] New issue where bot will not store warnings

### ISSUE THREAD

**Issue by JjTheHusky** [GilbertGobbels/GAwesomeBot#105]
Hi, just recently I discovered my bot wasn't recording strikes to the database.
I have tried downloading fresh copies of the dev builds, and dropping the database, but its an issue in the code.
I have went as far as to do a full linux os reinstall. Still the same issue.
The bot will still post it to a modlog channel and dm the user.

**Comment by JjTheHusky** [comment]
Update, it appears more stuff like trying to update the prefix from command, doesnt update in web panel. I would investigate quickly.

**Comment by KingDGrizzle** [comment]
Currently, it seems like `mongoose.Promise = require("bluebird");` in Database/Driver.js _might_ cause these issues.

Testing *has* to be done, so don't take my word.

**Comment by scarecr0w12** [comment]
Noticed something while looking at this my self (Which btw commenting out the bluebird line does fix things, with out further problems it seems). But i found that prior to doing the commenting out, bot IS saving strikes, but only some. 

I tried to run a eval with a javascript code it blocked out. It filtered it and added a strike, which was atleast view-able from admin panel

**Comment by scarecr0w12** [comment]
Also too add, again, was only viewable from admin panel, i was not able to run '-strikes' and see it as a strike

**Comment by theanidox** [comment]
I've had the bluebird line commented out for a while and I've had no issues with the bot.

**Comment by KingDGrizzle** [comment]
Should be fixed now, AFK command fix will replace bluebird with a global Promise library
