### ISSUE TITLE
[Web Request] Use more POST than refresh

### ISSUE THREAD

**Issue by KingDGrizzle** [GilbertGobbels/GAwesomeBot#108]
This is a suggestion from me friend @theHaden , as we are using too many refreshes when we remove things like status messages. We could make them use POST, OR queue the changes till you click "save"

**Comment by GilbertGobbels** [comment]
Yup, Gilbert approves

**Comment by theHaden** [comment]
I'd prefer if it queued changes until 'save' is hit as opposed to instantly applying using POST

**Comment by GilbertGobbels** [comment]
I agree, POSTing every change could lead to heavy performance drops client- and serversided.

**Comment by theHaden** [comment]
I can imagine it'd be simple enough too, just an array of JavaScript Objects containing the data to be sent to the server?

**Comment by vladfrangu** [comment]
Been here, done this. Well, Gilbert did this. 🎉
