### ISSUE TITLE
[Request] Get a /dashboard/other/import option

### ISSUE THREAD

**Issue by KingDGrizzle** [GilbertGobbels/GAwesomeBot#116]
It would be nice to get a /import, so we can finally use that export feature that we had.

Otherwise, make it a text box that just accepts the JSON, and sets the bot based on it

**Comment by theanidox** [comment]
Export/import for bot settings backups?

**Comment by KingDGrizzle** [comment]
Export already exists, we need an import tho

**Comment by theanidox** [comment]
Being able to import stuff would be cool (I'd back up my settings, maybe being able to transfer settings to other servers through this.)
