### ISSUE TITLE
[Implemented soonTM] New package.json

### ISSUE THREAD

**Issue by KingDGrizzle** [GilbertGobbels/GAwesomeBot#117]
As we're aproaching v4.1, I'd say we should get a new package.json. Theres things that don't need to be there (like bufferutil) and things that work just fine in newer versions.

~I've been currently working on a "new" one, and I'll Pr it and wait for opinions~

- [x] Remove bufferutil
- [x] Remove bluebird
- [x] Add String (`"string": "*"`)
- [x] Change random-puppy to random-animal
- [x] ~~Replace "money"~~ Fix money

**Comment by theHaden** [comment]
Make sure you're using `npm uninstall --save <package-name>` when removing a node module from the project. (The **--save** is important.) ;)

**Comment by JjTheHusky** [comment]
Issue fixed? 

~~should close~~

**Comment by KingDGrizzle** [comment]
Not issue, not fixed. When Pr is merged, this will close

Money api is already changed locally, with what seems like a very good replacement

**Comment by GilbertGobbels** [comment]
Discussion moved to #157
