### ISSUE TITLE
Bot not saving prefix

### ISSUE THREAD

**Issue by theanidox** [GilbertGobbels/GAwesomeBot#119]
I have my bot running on 2 servers, and on one the prefix saved, but on the other it stayed as `@botname` after I set it to `fb!` . I've had this issue before when trying to set the prefix as `/` , but after I changed it to `!fb` on the first server and then it worked. Changing it on the second server simply does nothing.

![lbl](https://cloud.githubusercontent.com/assets/24899167/24300831/a227588a-10a5-11e7-884e-bdc5af67f279.png)

As you can see from the screenshot, it says it changes, but only responds to `@botname`

**Comment by JjTheHusky** [comment]
This is a database saving issue, related in #105
Simply goto Database/Driver, and remove the second line
“mongoose.Promise = require("bluebird");”
Restart the bot and try again.

**Comment by theanidox** [comment]
Thanks, this worked!
