### ISSUE TITLE
"Repository doesn't exist, either you don't have access"

### ISSUE THREAD

**Issue by potaha** [GilbertGobbels/GAwesomeBot#123]
I always get this piece of error, when i do `npm install`.
`npm ERR! Windows_NT 10.0.15055
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\owner\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:abalabahaha/eris.git C:\Users\owner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-abalabahaha-eris-git-dev-74d17fbb
npm ERR! Cloning into bare repository 'C:\Users\owner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-abalabahaha-eris-git-dev-74d17fbb'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\potahabot\GAwesomeBot\npm-debug.log`

**Comment by KingDGrizzle** [comment]
Not our fault, but Eris's fault.

**Comment by potaha** [comment]
Nvm, fixed it.
