### ISSUE TITLE
Remove "Require email in discord login oauth"

### ISSUE THREAD

**Issue by JjTheHusky** [GilbertGobbels/GAwesomeBot#124]
Some people are complaining to me that why they need their email with logging in, and it's questioning me why?

It's not needed right? :P I've already tried going to the login screen and removing the `identify%20email%20` from the URL, and I got in just fine.

Just a small thing, but I've gotten a few messages from people saying I'll steal their email.
`¯\_(ツ)_/¯`

**Comment by scarecr0w12** [comment]
Pretty sure it doesn't matter seeing as the authorization is through discord and not via your files/site

**Comment by KingDGrizzle** [comment]
Don't get why they'd be afraid about that. I'd have to see why the bot uses the email currently, if it can be removed from the code.

But it goes from Discord. To the bot. Its not like you can hook into it and steal emails, its not possible afaik.

**Comment by theanidox** [comment]
Yeah, I don't think it would be possible to steal their email addresses but I don't see any reason for it to have it.

**Comment by JjTheHusky** [comment]
Opened Pull Request to remove in #152
