### ISSUE TITLE
[Issue] Discord's new "Auto Moderation" Causing optimization issues

### ISSUE THREAD

**Issue by JjTheHusky** [GilbertGobbels/GAwesomeBot#125]
Recently since the new security thing where it auto-moderates "NSFW" content, it has recently caused some issues with my bot.

I believe it's not just my bot, rather anyone using GAB, from it slowing down, to it not being able to post anything sometimes
`
 (node:8193) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): Error: 400 BAD REQUEST on POST /channels/295370522                                                                                898989057/messages
 {"code": 20009, "message": "Explicit content cannot be sent to the desired recipient(s)"}
`
I'm not sure if this is fixable, but I might as well post it.

**Comment by KingDGrizzle** [comment]
As I've mentioned, this is NOT a bot's error. We cannot do anything, but possibly remove the nsfw commands as they are affected by this

**Comment by JjTheHusky** [comment]
I don't think that's a good idea lol, I did notice a lot of people use the... naughty commands on my bot... hence it's name *cough*
I'll just close it, I don't know what I was thinking. But It was strange because this was happening on servers where I've disabled the moderation, but still gave out the error

**Comment by KingDGrizzle** [comment]
As for the moderation off - bot still gets moderated, its a known bug by discord
