### ISSUE TITLE
[Request] A way to get the web dashboard on Heroku

### ISSUE THREAD

**Issue by theanidox** [GilbertGobbels/GAwesomeBot#126]
Currently, I host my bot on Heroku. It works OK for me except I can't get the web dashboard. I need it for one reason: setting the moderator role. If theres any way to get web dashboard or change it without, help pls :S

**Comment by KingDGrizzle** [comment]
It wouldn't be on our side, but Heroku's. Ask them first about it, but as the IP is dynamic, it might not be doable
