### ISSUE TITLE
Extension not working? [probably just my bad coding skills]

### ISSUE THREAD

**Issue by theanidox** [GilbertGobbels/GAwesomeBot#131]
I'm trying to make an authentication command, this is the code I have
http://i.imgur.com/dhZ9KQ7.png
When I type /auth , nothing happens and the role doesn't add.
Am I doing I wrong?
I've tried doing //auth too.

[By the way, I'm using AuroraBot]

**Comment by KingDGrizzle** [comment]
Yes, your doing it wrong. Read the wiki post on extensions and see if you figure it out. If you don't, ping me in Discord
