### ISSUE TITLE
Don't use random-puppy

### ISSUE THREAD

**Issue by GregoryGregoryGregory** [GilbertGobbels/GAwesomeBot#134]
The !dog command frequently returns an error from Imgur saying the image does not exist. I'm sure there's a better module / api to use for this command, I've had the same issue with random-puppy.
EDIT: [I made something to combat the issue](https://www.npmjs.com/package/random-animal)

![:eyes:](http://i.imgur.com/etoqSKN.png)

**Comment by KingDGrizzle** [comment]
Considered in #117
