### ISSUE TITLE
[Bug] Timed Actions don't update without a restart

### ISSUE THREAD

**Issue by Blazeflack** [GilbertGobbels/GAwesomeBot#137]
When creating a new timer extension, it will never execute at the desired interval until a bot restart has been performed.

In the same vein, changing the interval for the timer extension will not take effect until after a restart. It will continue using the old interval until a restart has been performed.

This bug affects the "Message of the Day" functionality as well. Any changes to the settings will not take effect until after a restart of the bot.

**Comment by Blazeflack** [comment]
Deleting a timer extension will not take effect either until a restart is performed. Even after being deleted the timer extension will continue running at the interval it was created with (according to the logs).

**Comment by Blazeflack** [comment]
This bug affects the "Message of the Day" functionality as well. Any changes to the settings will not take effect until after a restart of the bot.

**Comment by vladfrangu** [comment]
We'll handle MOTD, dunno about timer extensions, we'll need to look into those

**Comment by vladfrangu** [comment]
@Blazeflack can you elaborate some more on the timer extensions? I need as much details so I know what I need to do.

So, updating the interval won't update in the extension? Thats easy to fix (I hope)

And deleting the extension still keeps it in a loop?

**Comment by Blazeflack** [comment]
Yes, that is correct. Any change you make to a timer extension has no effect until after a restart. Adding a timer extension will require a restart too before it actually starts working.

**Comment by vladfrangu** [comment]
MOTD has been tested and its officially fixed! 🎉 

As for extensions.. They can wait :D

**Comment by Gilbert142** [comment]
Fixed in indev.
