### ISSUE TITLE
[Bug] Timer Extensions return channel IDs from another Guild

### ISSUE THREAD

**Issue by KingDGrizzle** [GilbertGobbels/GAwesomeBot#138]
Expecting the result to be the same even after a reboot.

So, you have Guild 1 with a set of channels, and guild 2 with a set of channels.

IF you do a `channel.guild.channels.map(ch => {channel.createMessage(ch.name + " is in guild " + ch.guild.name)})`, you'll see that you get a set of channels from a completely different guild

This breaks. EVERYTHING. And anything.

**Comment by KingDGrizzle** [comment]
This **only applies to timer extensions**

**Comment by HilbertGilbertson** [comment]
So on my build I added a timer extension with the code `channel.guild.channels.map(ch => {channel.createMessage(ch.name + " is in guild " + ch.guild.name)})` and it shows me all the channels on the guild where the timer extension runs. It does *not* show me channel names from other guilds.

**Comment by vladfrangu** [comment]
This won't be an issue / isn't really an issue cause new API.
