### ISSUE TITLE
Error with "Length" when accessing (siteurl)/dashboard

### ISSUE THREAD

**Issue by ItsLachy** [GilbertGobbels/GAwesomeBot#14]
`0|GAwesome | TypeError: Cannot read property 'length' of undefined
0|GAwesome |     at addServerData (/root/GAwesomeBot/Web/WebServer.js:1693:25)
0|GAwesome |     at app.get (/root/GAwesomeBot/Web/WebServer.js:1725:4)
0|GAwesome |     at Layer.handle [as handle_request] (/root/GAwesomeBot/node_modules/express/lib/router/layer.js:95:5)
0|GAwesome |     at next (/root/GAwesomeBot/node_modules/express/lib/router/route.js:131:13)
0|GAwesome |     at Route.dispatch (/root/GAwesomeBot/node_modules/express/lib/router/route.js:112:3)
0|GAwesome |     at Layer.handle [as handle_request] (/root/GAwesomeBot/node_modules/express/lib/router/layer.js:95:5)
0|GAwesome |     at /root/GAwesomeBot/node_modules/express/lib/router/index.js:277:22
0|GAwesome |     at Function.process_params (/root/GAwesomeBot/node_modules/express/lib/router/index.js:330:12)
0|GAwesome |     at next (/root/GAwesomeBot/node_modules/express/lib/router/index.js:271:10)
0|GAwesome |     at Layer.handle [as handle_request] (/root/GAwesomeBot/node_modules/express/lib/router/layer.js:91:12)
0|GAwesome |     at trim_prefix (/root/GAwesomeBot/node_modules/express/lib/router/index.js:312:13)
0|GAwesome |     at /root/GAwesomeBot/node_modules/express/lib/router/index.js:280:7
0|GAwesome |     at Function.process_params (/root/GAwesomeBot/node_modules/express/lib/router/index.js:330:12)
0|GAwesome |     at next (/root/GAwesomeBot/node_modules/express/lib/router/index.js:271:10)
0|GAwesome |     at app.use (/root/GAwesomeBot/Web/WebServer.js:163:3)
0|GAwesome |     at Layer.handle [as handle_request] (/root/GAwesomeBot/node_modules/express/lib/router/layer.js:95:5)
0|GAwesome |     at trim_prefix (/root/GAwesomeBot/node_modules/express/lib/router/index.js:312:13)
0|GAwesome |     at /root/GAwesomeBot/node_modules/express/lib/router/index.js:280:7
0|GAwesome |     at Function.process_params (/root/GAwesomeBot/node_modules/express/lib/router/index.js:330:12)
0|GAwesome |     at next (/root/GAwesomeBot/node_modules/express/lib/router/index.js:271:10)
0|GAwesome |     at SessionStrategy.strategy.pass (/root/GAwesomeBot/node_modules/passport/lib/middleware/authenticate.js:325:9)
0|GAwesome |     at /root/GAwesomeBot/node_modules/passport/lib/strategies/session.js:65:12`

URL: https://bot.lachy.io/dashboard

**Comment by KingDGrizzle** [comment]
Can you attempt a fresh install of the developer branch and see if this happens?

**Comment by ItsLachy** [comment]
Fixed.

**Comment by ItsLachy** [comment]
I needed to install mongodb, which I skipped.
