### ISSUE TITLE
[Suggestion] NSFW commands to only work in "NSFW-" channels

### ISSUE THREAD

**Issue by JjTheHusky** [GilbertGobbels/GAwesomeBot#142]
To help protect the sake of other servers, and potentially our bots;
Discord now allows you to essentially post NSFW content in an NSFW specified channel (Channel will start with "nsfw-")
We should make a check flag in the NSFW commands to check if the channel is marked "nsfw-"

This would help servers to not get in trouble because they did it in a non-NSFW channel.
(I don't think it would be our bots fault, but it's better safe than sorry)
Essentially if this idea is considered, it should post a message to the channel the user tried to use the NSFW command in, telling them it can only be done in an NSFW channel.

**Comment by KingDGrizzle** [comment]
Will do

**Comment by TTtie** [comment]
Eris now has [`GuildChannel.nsfw`](https://abal.moe/Eris/docs/GuildChannel#property-nsfw) for that

**Comment by KingDGrizzle** [comment]
~~and nobody cares, its already covered in #157 ~~

**Comment by KingDGrizzle** [comment]
Since #157 will handle this, i will close this, thanks for the suggestion 👍
