### ISSUE TITLE
cat and dog commands are broken

### ISSUE THREAD

**Issue by Blazeflack** [GilbertGobbels/GAwesomeBot#143]
The following error is thrown:

```javascript
info: Treating '!cat' as a command svrid=209321873966759936, chid=209321873966759936, usrid=165229358884192256
error: Failed to process command 'cat' { svrid: '209321873966759936',
  chid: '209321873966759936',
  usrid: '165229358884192256' } TypeError: bot.getPublicCommand(...) is not a function
    at db.users.findOrCreate.err (/home/blazeflack/bot/Events/messageCreate.js:543:49)
    at /home/blazeflack/bot/node_modules/mongoose-findorcreate/index.js:31:11
    at Query.<anonymous> (/home/blazeflack/bot/node_modules/mongoose/lib/model.js:3731:16)
    at /home/blazeflack/bot/node_modules/kareem/index.js:277:21
    at /home/blazeflack/bot/node_modules/kareem/index.js:131:16
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

According to Scarecr0w12 in the GAwesomeBot Discord, this was caused by changes @GregoryGregoryGregory made.

**Comment by KingDGrizzle** [comment]
This issues happen when either a dependency is missing. If you'd reload the command by using `reload cat`you'd see the issue is a missing dependency. Same applies to pokedex, with missing the string dependency. #117

**Comment by Blazeflack** [comment]
If that's the case, shouldn't the missing dependency be added to the package.json then?

**Comment by KingDGrizzle** [comment]
#117 considers it 👍

**Comment by KingDGrizzle** [comment]
247609147f561598ed11272de19323bb1a230b71

**Comment by Blazeflack** [comment]
Alright, good.

It might be a good idea to either disallow pull requests if they need changes to package.json, or allow that the pull requests contain changes to package.json too.

It isn't ideal having to manually install various dependencies when the package.json exists for that.
