### ISSUE TITLE
[Bug] Timed Actions don't update without a restart

### ISSUE THREAD

**Issue by KingDGrizzle** [GilbertGobbels/GAwesomeBot#147]
This applies to timer extensions, messages of the day, etc. You basically need a restart to fix this

**Comment by Blazeflack** [comment]
Duplicate of #137

**Comment by KingDGrizzle** [comment]
More like addendum

**Comment by Blazeflack** [comment]
No need to create a separate ticket just to mention it affects message of the day too. Just add it to the original ticket :P

**Comment by KingDGrizzle** [comment]
#137
