### ISSUE TITLE
[Suggestion] Add server blacklist

### ISSUE THREAD

**Issue by JjTheHusky** [GilbertGobbels/GAwesomeBot#155]
Theoretically, a server blacklist would make the bot leave a blacklisted server.

How it works:

When someone invites a bot, the bot checks the server ID list to see if it is on a black list.

If it is not there, the server adds the bot normally.

If it is there, the bot will automatically leave the server.

I've been having issues where people are inviting my bot to a server and negatively mess with it, usually spamming it which lowers that send message rate limit.

**Comment by GilbertGobbels** [comment]
Sounds good, I'll work on this after updating and try to push this out for either V4.0.3 or V4.1

**Comment by theanidox** [comment]
:ok_hand:

**Comment by vladfrangu** [comment]
a1e414db1366e4d52042daedb31a6f92d2b26a71
9fb4455371bc3a8df806a8f47a9734d76a269c74

And more! We've heard your calls!
