### ISSUE TITLE
[Suggestion] Allow eval in the maintainer console

### ISSUE THREAD

**Issue by KingDGrizzle** [GilbertGobbels/GAwesomeBot#163]
*cough* @BitQuote suggested this

**Comment by BitQuote** [comment]
You have no evidence that I suggested anything.

**Comment by KingDGrizzle** [comment]
[Never be it forgotten that BitQuote actually said this](https://i.kingdgrizzle.ml/2017/05/k078J7.png)

**Comment by BitQuote** [comment]
Photoshopped.

**Comment by GilbertGobbels** [comment]
Inspect element.

**Comment by KingDGrizzle** [comment]
🤣

**Comment by theHaden** [comment]
Firefox Developer Tools™

**Comment by theHaden** [comment]
In a Chrome-based application.

Trust me, @KingDGrizzle would find a way.

**Comment by KingDGrizzle** [comment]
Once a hacker, always a hacker 👀

**Comment by BitQuote** [comment]
He might be using the Discord web app in Firefox.

**Comment by KingDGrizzle** [comment]
[Indeed I am](https://i.kingdgrizzle.ml/2017/05/w8w1J5.png)

**Comment by BitQuote** [comment]
But that's Chrome.

**Comment by KingDGrizzle** [comment]
*Exactly*

**Comment by BitQuote** [comment]
Why do you have the discord.js docs open in 4 separate tabs?

**Comment by KingDGrizzle** [comment]
4 different Discord.JS functions

**Comment by BitQuote** [comment]
And what's that *Discord HOLY SHIT* folder?

**Comment by KingDGrizzle** [comment]
*[Nothing Important](https://i.kingdgrizzle.ml/2017/05/A5G1X9.png)*

**Comment by theHaden** [comment]
In my time, runnin' this crew
I only ever met one joker as daft you.
He thinks he cool, got an eye on memes.
Let me tell you son, harder than it seems.
A master of silence, after a joke,
awkward moments from awkward folk.
It's something to do when I get bored,
Roast that kid, Super Not from Discord.
Now some real talk for a second,
he's got some real skill with which to beckon.
It ain't easy, stayin' in check,
When all you know how to do is get wrecked.
Don't go gettin', the wrong impression.
We're almost done with the roasting session.
I have one more point, I'd like to make
From this rap, one thing to take.
I love all my Bug Hunter™s, even you
Love all my friends...


Expect Dru.

**Comment by KingDGrizzle** [comment]
HOLY FUCKING SHIT?!

**Comment by BitQuote** [comment]
18 comments on an issue. Wow.

**Comment by KingDGrizzle** [comment]
Make that 20 so we can meme it up

**Comment by BitQuote** [comment]
It's 21 now.

**Comment by KingDGrizzle** [comment]
English or it never happened!

**Comment by JjTheHusky** [comment]
FOX KIDKILLER KNIFE SHOOT CAT MADACHAROD

**Comment by TTtie** [comment]
it's a gr8 suggestion i r8 8/8

**Comment by GregoryGregoryGregory** [comment]
All these issues and PRs make me sad, just fork red :^)

**Comment by TTtie** [comment]
>fork red

nothx

**Comment by GregoryGregoryGregory** [comment]
no u

**Comment by KingDGrizzle** [comment]
> no u

~no u~

**Comment by vitalkanev** [comment]
>no u
>>~~no u~~
>
👀  *lmao* WTF is happening here

**Comment by theanidox** [comment]
MSPaint'ed

**Comment by theanidox** [comment]
Whoever said it, it'd be a pretty cool idea tho.

**Comment by SunburntRock89** [comment]
>Never let it be forgotten
>404 Not Found

**Comment by vladfrangu** [comment]
Oh uh. This has been done. Soo.
