### ISSUE TITLE
The extension file download returns the filename wrapped in quotes

### ISSUE THREAD

**Issue by TTtie** [GilbertGobbels/GAwesomeBot#170]
I don't even know if it's an issue tbh

**Comment by KingDGrizzle** [comment]
Example?

**Comment by TTtie** [comment]
@KingDGrizzle [Link](https://bot.gilbertgobbels.xyz/extension.abext?extid=5931854b92c6b818606f9bf9)

**Comment by KingDGrizzle** [comment]
I tried your link, and it worked just fine, no quotes.. Can you provide ***exact*** repro steps?

**Comment by TTtie** [comment]
1. Use Firefox, no matter mobile/desktop
2. Go to the link
3. ???
4. Profit!

**Comment by KingDGrizzle** [comment]
Well I can't repro on chrome, so it might be a Firefox-only issue, wich would be shitty tbh

**Comment by TTtie** [comment]
Idk if it's reproducible with IE

**Comment by TTtie** [comment]
I guess I gotta close this as this is a third party issue, which GAB devs wontfix.
