### ISSUE TITLE
[Issue] Bot cannot log message deletes or message edit's correctly

### ISSUE THREAD

**Issue by JjTheHusky** [GilbertGobbels/GAwesomeBot#171]
Trying to do either outputs errors to the console, and does not log the messages in a specified channel.

Logs are here: https://hastebin.com/azakazexib.pas

**Comment by TTtie** [comment]
Fix PR is in #172 now

**Comment by TTtie** [comment]
Somebody should close this issue, https://github.com/GilbertGobbels/GAwesomeBot/commit/a590a113f90a835d7f0481bb7be011e086543dbc
