### ISSUE TITLE
[Issue] Voicetext channels can't function properly

### ISSUE THREAD

**Issue by JjTheHusky** [GilbertGobbels/GAwesomeBot#175]
Voicetext channels are very funky as they are coded right now.

The only way to get voice text channels to function properly:

When you join a voice channel, the bot gives you access to the voicetext channel, however, if you want to join a different channel, you have to first leave the current one, and join the new one, otherwise the old voicetext channel will stick to you until you join the voice channel for it and leave it, and even then, sometimes the bot doesn't even remove the access to the text channel.

I hope we can resolve this before pushing out the new release.

**Comment by Gilbert142** [comment]
Fixed in indev branch.
