### ISSUE TITLE
Cannot read property 'catch' of undefined

### ISSUE THREAD

**Issue by succ95** [GilbertGobbels/GAwesomeBot#176]
the bot keeps crashing when i say anything to the bot it crashes

**Comment by KingDGrizzle** [comment]
Are you using the master branch? Are you using Node v8? Please give as MUCH detail as possible.

**Comment by succ95** [comment]
I Am Using Development Branch On Node v6

**Comment by KingDGrizzle** [comment]
Interesting... Mind placing the crash log here?

**Comment by succ95** [comment]
nevermind i fixed it
