### ISSUE TITLE
[Bug] Almost every external API command isn't working

### ISSUE THREAD

**Issue by TTtie** [GilbertGobbels/GAwesomeBot#178]
List of the affected things will be posted below.

**Comment by TTtie** [comment]
- Jokes
- IMDB (#179)

**Comment by TTtie** [comment]
- Stocks

**Comment by TTtie** [comment]
- Memes

**Comment by TTtie** [comment]
> `dgg` seems to be broken too
Once shows No results, then nothing happens
Screenshot 1 (link) and then Screenshot 2 (link), where nothing happens (Click on the links)


The json format is returning no results, even when the web version displays some.

**Comment by KingDGrizzle** [comment]
Ddg wise, it might be the api itself. We could make a poll on whether to leep ddg.

IMDb was already explained, we would currently need to pay for a key.

Memes afaik was already replaced, but needs implementation.

Jokes and stock, please provide some other variants

**Comment by TTtie** [comment]
:thinking:

**Comment by KingDGrizzle** [comment]
IMDb will be fixed, ~unless they change the API again!~

**Comment by vladfrangu** [comment]
IMDb is fixed

Memes api seems to be back.. again? dunno

Stock: does anyone even use it?

Jokes: temp replaced

**Comment by Gilbert142** [comment]
Fixed in indev branch.
