### ISSUE TITLE
IMDB Command Broken

### ISSUE THREAD

**Issue by Kyle2000** [GilbertGobbels/GAwesomeBot#179]
The IMDB command always returns `Nothing found on IMDB`. I think it is an error with the API GAB is using.

**Comment by TTtie** [comment]
Confirmed to not be working
![img](https://owo.solutions/fc6d65.png)

**Comment by KingDGrizzle** [comment]
Its not a bug, currently we'd need to pay for an license key

**Comment by TTtie** [comment]
>we'd need to pay for an license key

truedat

**Comment by Minionjosh** [comment]
How much is a licence key tho?

**Comment by KingDGrizzle** [comment]
Around 1$, or wait till they go back to free, as from what the Patreon said, they will be working on rate limitations and such

**Comment by Minionjosh** [comment]
...... could i throw that dollar to give a licence key to make it work .... ;)

**Comment by KingDGrizzle** [comment]
I'd suggest asking Gilbert, but remember. Its per-month or till the API is finally free

**Comment by Minionjosh** [comment]
1 dollar a month is nauthing

**Comment by Minionjosh** [comment]
..... Gilbert ..... You now need to do some work ...

**Comment by KingDGrizzle** [comment]
I'll move this to #178, so closing
