### ISSUE TITLE
YouTube Command Borken

### ISSUE THREAD

**Issue by Kyle2000** [GilbertGobbels/GAwesomeBot#180]
https://i.kyle2000.ml/DiscordCanary_2017-06-10_09-34-39.png This screenshot shows that using GAB, I was not able to find anything, but when using my bot(that uses the same NPM module to search for YouTube videos) returns a video. Also: Nothing appears to work with YouTube

**Comment by TTtie** [comment]
You seem to use a selfhosted instance. On official GAB it clearly works.

**Comment by TTtie** [comment]
Can you please tell what branch are you on?

**Comment by Kyle2000** [comment]
What do you mean?

**Comment by KingDGrizzle** [comment]
This seems like a local issue with either your self-host OR your key. Unless you can show otherwise, its not an issue

**Comment by TTtie** [comment]
^

**Comment by Kyle2000** [comment]
Oh, OK

**Comment by KingDGrizzle** [comment]
![api's GAB has on](https://i.kingdgrizzle.ml/2017/06/n5B590.png)
