### ISSUE TITLE
[Suggestion] Make soft-ban command act like other bots

### ISSUE THREAD

**Issue by JjTheHusky** [GilbertGobbels/GAwesomeBot#181]
Soft-ban on other bots bans the user, and unbans them, this is usually done to get rid of the messages.

Pretty simple explanation lol

Just an idea that came up in my mind :P

**Comment by ffxhand** [comment]
inb4 **But We're Different!™**

**Comment by KingDGrizzle** [comment]
~~But We're Different!™️~~

**Comment by Kyle2000** [comment]
Sounds like a good idea. We could just rename the `softban` command to something else (like` clearban` or `cban`, `idk`), and then in place of the old-softban command, put a command that bans the user, deletes all messages, then unbans. But you could also use `nuke <user> <message count>` to delete messages by the user without banning.

**Comment by KingDGrizzle** [comment]
`Softban` works by banning the user, without removing his / hers / its messages.

A new ban command could be easily done, but I don't *really* see its need

**Comment by theanidox** [comment]
@Kyle2000 The only  problem with nuke is it doesn't always remove all of the messages. I think this would be cool. :+1:

**Comment by KingDGrizzle** [comment]
Let me correct you. The Discord API prevents any bot from bulk deleting messages that are older than 2 weeks. Meaning, the bot will just ignore them.

In some APIs, like Discord.JS, theres an option to delete the even older ones, at who knows what price.

**Comment by ffxhand** [comment]
@theanidox As far as I know, there's no way to remove all of a user's messages anyway. *Definitely* not those older than 2 weeks. Nuke takes in the message count as a number of messages to search, then deletes the ones it finds — not the most recent of that number of messages which match the query.

**Comment by ffxhand** [comment]
Anyway: softban in GAB is different but it definitely serves a useful purpose. I've used both standard ban and softban in different cases, both for legitimate practical purposes. However, I don't see the practical use of a ban-nuke-unban function.

**Comment by KingDGrizzle** [comment]
You have the extension API at your hands. ~Abuse~ Use it 😛

**Comment by Gilbert142** [comment]
Closing until someone else wants to argue for the ban-nuke-unban command.
