### ISSUE TITLE
wont find members by their current usernames 

### ISSUE THREAD

**Issue by Sirred90** [GilbertGobbels/GAwesomeBot#183]
Profile command for GAwesomebot is displaying previous usernames of users will not search using current username, it states that it cannot find the member, makes it hard to use any of the commands for the bot as it effects the strike kick and ban commands too along with the logs it posts for strikes and or join/leave server, or ban.

**Comment by KingDGrizzle** [comment]
This seems to be a desync of sorts. For the profile command, I do have a slight fix, but it will come in 4.0.2

**Comment by vladfrangu** [comment]
Bug is because we disabled PRESENCE_UPDATES in the GAB, so this is resolved in a way
