### ISSUE TITLE
!tag command error when tags contain text with length over 2000

### ISSUE THREAD

**Issue by Blazeflack** [GilbertGobbels/GAwesomeBot#185]
When you use the !tag command without arguments, in order to print a list of tags, you will get an error if your tags contain text that makes the "content" length over 2000.

![unavngivet](https://user-images.githubusercontent.com/495947/27732514-f8708c14-5d91-11e7-91af-a6ed7fed0013.png)

This was experienced on the current master branch with Ubuntu 16.04 and NodeJS 7.10

**Comment by Blazeflack** [comment]
I suggest that the !tag command checks the length of the content it attempts to post and then splits it up into several messages if needed.

**Comment by KingDGrizzle** [comment]
Oui, will be handled in #184

**Comment by vladfrangu** [comment]
https://github.com/GilbertGobbels/GAwesomeBot/commit/5b33badf8eeaf0f0dcc7e972c71d607b1918d895
