### ISSUE TITLE
Errors in trivia questions

### ISSUE THREAD

**Issue by Gilou2** [GilbertGobbels/GAwesomeBot#187]
There are some errors in trivia questions, i checked them and noticed these : 

- [ ] Q : "This protein makes the blood red in color.",     R : "Haemoglobin",     Should be : "Hemoglobin"
- [ ] Q : "How many days where there in 1976?",     R : "three hundred and sixty six",     Should be : "366" (more intuitive)
- [ ] Q : "What comic strip character is Beetle Bailey's sister?",     R : "Lois (of Hi and Lois)",     Should be : "Lois"
- [ ] Q : "What was Daffy Duck's favorite insult?",     R : "You're dispicable!",     Should be : "You're despicable!"
- [ ] Q : "Name one male fish that gives birth?",     R : "sea horse or pipe fish",     Should be : "sea horse" (or "pipe fish")

And i just realized that the list is very long and i don't want to spend my night on it, but if i notice other errors i'll reoprt them ^^

**Comment by TTtie** [comment]
oh god, we gotta blame old AB devs

**Comment by KingDGrizzle** [comment]
Nice catches, they will defo get fixed. For *or* responses, it might be harder to handle multiple answers without a slight rewrite, but doable non the less.

If you manage to find any more issues, edit your main report and we'll fix them. Make them a checklist as well so you know when its fixed

**Comment by vladfrangu** [comment]
https://github.com/GilbertGobbels/GAwesomeBot/commit/e19fd3bade9d0c3bbc1fdcb8df7c242ebec0b73d
Fixed, if you find any more, please make a new issue
