### ISSUE TITLE
I think I found an error in Indev-4.0.2's info command

### ISSUE THREAD

**Issue by Kyle2000** [GilbertGobbels/GAwesomeBot#193]
https://i.kyle2000.ml/DiscordCanary_2017-07-17_13-06-08.png

As you can see in this screenshot the info command's embed says "Owned by undefined"

if you look at the code for the command [here](https://github.com/GilbertGobbels/GAwesomeBot/blob/indev-4.0.2/Commands/Public/info.js)  The value is `msg.channel.guild.members.get(msg.channel.guild.ownerID).tag`. 

https://i.kyle2000.ml/DiscordCanary_2017-07-17_13-07-41.png

As you can see this value returns `undefined`

**Comment by KingDGrizzle** [comment]
And thats cause someone doesn't have the objectdefines..

**Comment by TTtie** [comment]
^

**Comment by TTtie** [comment]
we should close as wontfix

**Comment by KingDGrizzle** [comment]
Eh, keep it.. you all are going to get mega surprised soon

**Comment by TTtie** [comment]
by the indestructible union of free republics?
