### ISSUE TITLE
[Bug] anime API broken

### ISSUE THREAD

**Issue by HilbertGilbertson** [GilbertGobbels/GAwesomeBot#20]
Not a bug with (G)AB itself, but the Hummingbird API (which anime.js uses) has been scrapped. Its replacement, the Kitsu API, is very new (last month) and application registration is soon to be introduced (see [here](https://forums.hummingbird.me/t/kitsu-api-documentation/33367) and [here](http://docs.kitsu17.apiary.io/#introduction/authentication)).

Once the Kitsu API introduces application registration (it looks as though public API keys [per the first link above] are to be phased out), anime.js can be updated, along with auth.json to support self-hosters' API keys. Either that, or the anime command could be scrapped.

**Comment by GilbertGobbels** [comment]
I'll keep an eye out on when registration is open to have a look.

**Comment by HilbertGilbertson** [comment]
I've added a provisional fix for the anime command. In the long run it is best to wait for the Kitsu API to open application registration (although we've no idea when that will be). But in the meantime the command should either be working or removed.

**Comment by GilbertGobbels** [comment]
Fixed in #85
