### ISSUE TITLE
[Proposal] Change how routes are handled, by switching to a class-based model

### ISSUE THREAD

**Issue by vladfrangu** [GilbertGobbels/GAwesomeBot#207]
## Proposal: Make WebServer ~great again~ more organized and easy to understand

Currently, our webserver.. is a mess. Very unorganized, all in one file, and its an ass to maintain. We'd like to change that, to make our life easier in the long run.

As such, I propose a more organized routing system and webserver. Routes would be classes, and each folder would represent the sub-path. If you'd have `api/userlist.js`, that would mean `hostingURL/api/userlist` or whatever it is defined as in the constructor of the special route

This is not our priority right now, but would be good to implement. After the rewrite is finished (soon:tm:?), maybe we'll take a slight break then think about how we'll make this happen.

**Comment by TTtie** [comment]
#MakeGABsWebServerGreatAgain

**Comment by Gilbert142** [comment]
`[WebServer.js] is an ass to maintain` says a person who doesn't maintain WebServer.js :')

I'm not doing folder structures that mirror resource routes, and I will remaster the Web Interface when we do the framework overhaul (React.js, vue.js?).

**Comment by Gilbert142** [comment]
Get your tags in shape vlad!

**Comment by TTtie** [comment]
well I prefer (client-side) React; theoretically, we can go MLG and make it all API-based

**Comment by pedall** [comment]
I could basically help you with React

**Comment by TTtie** [comment]
same
