### ISSUE TITLE
Custom Commands

### ISSUE THREAD

**Issue by JGriffin34432** [GilbertGobbels/GAwesomeBot#213]
Custom Commands

**Please describe the problem you are having in as much detail as possible:**
The ability to add custom commands to the bot.

**Include some reproduction steps:**

**Further details:**

- [ ] The problem happens on the official GAwesomeBot
  - [ ] The problem occurs on a self-host
- Node.JS version (If applicable): v9.5.0
- Operating System (If applicable): Windows 10 Home Insider Preview
- GAwesomeBot version AND branch: the latest experimental build
- Priority this issue should have – please be realistic and elaborate if possible:
  - [ ] Low
  - [x] Medium
  - [ ] High

**Comment by wasdennnoch** [comment]
You can add custom commands on the master and experimental version using the web interface, it's called "Extensions". In the rewrite (development and indev-4.0.2) it's as so many things not yet implemented but will be soon™. But you can and will be able to create fully custom commands using node.js.

If you are having any other problem please describe them in detail.

**Comment by vladfrangu** [comment]
Dammit @wasdennnoch, always faster than me.

But yes, as he said, we have what are called "Extensions", which are of 3 types (soon:tm: to be 4)
Said types are:
- Command
- Keyword
- Timer

Command Extensions act like regular commands, except they have limited access to certain properties.
Keyword Extensions run when one of the set keywords is used in a message
Timer extensions run at the interval set and do certain things.

As said, in the rewrite, extensions (amongst other things), don't work / exist yet. But they will be back, and with many many improvements to make YOUR experience better! Spoilers? (There will be extensions that run on certain events and extension **redacted**, which will allow **redacted**.)

Thereby, I'm going to close this. If you have any further questions, go ahead and ask them in our [Dsicord Server](https://discord.gg/NZwzJ9Q)
