### ISSUE TITLE
Is there any DB alternative to mongodb?

### ISSUE THREAD

**Issue by vico93** [GilbertGobbels/GAwesomeBot#217]
Tried from all sorts to setup GAB, but it requires mongo >2.6, and raspbian doesnt ship a mongo with sufficient version via apt.

I tried to follow [this tutorial](https://andyfelong.com/2016/01/mongodb-3-0-9-binaries-for-raspberry-pi-2-jessie/) just to mess up more my system.

Is there any chance to install gab and use a database like sqlite or other?

**Comment by TTtie** [comment]
Question, what kind of Raspberry Pi you have?

**Comment by vico93** [comment]
3B. After talking with support staff on discord it seems if i want to run GAB i will need to compile a custom 64bit kernel/os since the latest builds of mongo are only for arm64, and my current os (rasbpian) are arm32.
I [tried to get help on raspberry pi subreddit](https://www.reddit.com/r/raspberry_pi/comments/8709gp/installing_mongodb_34_on_raspbian/), i hope they could help me. As for now, i will close the issue. Thanks for your patience.
