### ISSUE TITLE
📝 Commands aren't loaded properly

### ISSUE THREAD

**Issue by thehydrogen** [GilbertGobbels/GAwesomeBot#260]
**Please describe the problem you are having in as much detail as possible:**
Commands, that are implemented, will execute as not implemented as the shard has experienced a hiccup.

**Include some reproduction steps:**
Run a command on a specific shard

**Further details:**

- [x] The problem happens on the official GAwesomeBot
  - [x] The problem occurs on a self-host
- Node.JS version (If applicable):
- Operating System (If applicable):
- GAwesomeBot version AND branch: indev-4.0.2
- Priority this issue should have – please be realistic and elaborate if possible:
  - [ ] Low
  - [ ] Medium
  - [x] High

**Comment by thehydrogen** [comment]
![image](https://user-images.githubusercontent.com/34059898/39096378-8346949a-464f-11e8-9b80-f8d20e6fb109.png)

**Comment by TTtie** [comment]
Uh.. lemme step into this: [`Bug reports are currently ignored due to the early stage of development.`](https://github.com/GilbertGobbels/GAwesomeBot/tree/indev-4.0.2)

**Comment by thehydrogen** [comment]
Vlad told me to create an issue about it. @TTtie

**Comment by TTtie** [comment]
oh h*ck, some1 should update the readme
