### ISSUE TITLE
👽 createCipher and createDecipher are deprecated in node v10

### ISSUE THREAD

**Issue by TTtie** [GilbertGobbels/GAwesomeBot#277]
**Please describe the problem you are having in as much detail as possible:**
Not really for now. But once soon, it may break the whole bot by the said methods being removed.

**Include some reproduction steps:**
None

**Further details:**
[Check node.js changelog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.0.0)  
For information:  
- Key must be at most 32 bytes long
- IV (initialization vector) must be at most 16 bytes long by AES standards
- Moving to the IV variant of create(De)Cipher is breaking for instances using said version, but not the new ones.

- [x] The problem happens on the official GAwesomeBot
 - [x] The problem occurs on a self-host
- Node.JS version (If applicable): <10.0.0
- Operating System (If applicable): any
- GAwesomeBot version AND branch: 4.2 
- Priority this issue should have – please be realistic and elaborate if possible:
  - [ ] Low
  - [x] Medium
  - [ ] High

**Comment by Gilbert142** [comment]
All DeprecationWarnings are seen as bugs over here, we want to avoid all of them at any cost!

**Comment by TTtie** [comment]
Looks like it is just only deprecated on the documentation side for now.

However, using the specified methods in the title is insecure as stated [here](https://nodejs.org/api/deprecations.html#deprecations_dep0106_crypto_createcipher_and_crypto_createdecipher)

**Comment by TTtie** [comment]
Fixed with c8ef8ed.
