### ISSUE TITLE
[Issue/Bug] Error while automatically handling spam protection

### ISSUE THREAD

**Issue by JjTheHusky** [GilbertGobbels/GAwesomeBot#37]
https://hastebin.com/opimuyotaz.sql

Updated, this causes the bot to crash.

**Comment by KingDGrizzle** [comment]
Suggestion: Please use hastebin for errors, as its cleaner to see 😛

**Comment by JjTheHusky** [comment]
Updated.

**Comment by KingDGrizzle** [comment]
Code snip that breaks: https://hastebin.com/odurojeyul.vbs

**Comment by HilbertGilbertson** [comment]
Duplicate of #64 - or should I say that issue was a duplicate of this one. Already fixed in #65.

**Comment by KingDGrizzle** [comment]
Yet again, you dun goofed
It as nothing to do with that
Its the hey, your spamming and it can't save the spamDocument of the channelDocument of the serverDocument

**Comment by KingDGrizzle** [comment]
Yet again, I just guufed
Nevermind
