### ISSUE TITLE
❌ Cannot read property 'check' of undefined

### ISSUE THREAD

**Issue by thehydrogen** [GilbertGobbels/GAwesomeBot#465]
**Please describe the problem you are having in as much detail as possible:**
While running the latest commit of GAwesomeBot branch `indev-4.0.2`, an error occurred during the startup process of GAB and crashed the entire process.
```
[18:18:07] - error: [Master] An unknown and unexpected error occurred, and we failed to handle it. Sorry! x.x
 TypeError: Cannot read property 'check' of undefined
    at database.initialize.catch.then (C:\Users\Hydrogen\Documents\GitHub\GAwesomeBot-indev\master.js:69:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Include some reproduction steps (How can we cause the bug to happen?):**
Run the latest build of GAB indev branch.

**Further details:**
Has something to do with the database, guessing some faulty GADriver code. (naughty Gilbert)

- [ ] The problem happens on the official GAwesomeBot
  - [x] The problem occurs on a self-host
- Node.JS version (If applicable): v10.9.0
- Operating System (If applicable): Windows 10 Enterprise LTSB
- GAwesomeBot version AND branch: `indev-4.0.2 cb63e6a0686bedc42b4e814497ab5798a5a0fce3`
- Priority this issue should have – please be realistic and elaborate if possible:
  - [ ] Low (Only partially affects the usage of a feature or command)
  - [ ] Medium (Affects the full usage of a feature or command)
  - [x] High (Prevents the full usage of a feature or command)

**Comment by TTtie** [comment]
Can confirm that the error exists, across multiple GAB instances. This is probably just an overlook from migrating to `GAwesomeClient`, as Updater isn't defined anymore in `./Modules`:
https://github.com/GilbertGobbels/GAwesomeBot/blob/5278801f6d917ddab80c620e06d7b5f869ee98c3/master.js#L11
https://github.com/GilbertGobbels/GAwesomeBot/blob/5278801f6d917ddab80c620e06d7b5f869ee98c3/master.js#L69
https://github.com/GilbertGobbels/GAwesomeBot/blob/5278801f6d917ddab80c620e06d7b5f869ee98c3/Modules/index.js#L22-L26

Here's a temporary solution:
```
git checkout 343ec4ddc4dfb3f79fedbd0b66d5d088b3644832
```

**Comment by Gilbert142** [comment]
Sorry for the wait, everyone. Fixed in latest commit!
