### ISSUE TITLE
[bug] [userobject].createMessage in extensions won't work when passed through member object

### ISSUE THREAD

**Issue by HilbertGilbertson** [GilbertGobbels/GAwesomeBot#50]
In an extension, DMing the message author is easy (`message.author.createMessage('abc')`), but there seems to be no way to DM another user (e.g. a user by ID or by mention). The eris [User](https://abal.moe/Eris/docs/User) object contains the `getDMChannel()` function, which returns a channel object for the user (channel.createMessage), so they can be DM'd.

In extensions, User.js contains a `createMessage()` function which uses `erisUser.getDMChannel()`, so we can simply execute `[userobject].createMessage()` to DM the user. E.g. we can use `message.author.createMessage` (Message.js fetches the user object from User.js and returns this through _message.author_) in an extension.

But what if we don't have a user object for a user? e.g. we have a command extension where want to send a DM to a user by their UID.  In an extension, we can't get a user object by ID but we _can_ get the user's _Member_ object by `guild.members.get(UID)`. **Helpfully**, the eris [Member](https://abal.moe/Eris/docs/Member) object returns a `.user` property - providing GAB the user object and so `guild.members.get(UID).user` returns the user object from User.js.

**So what's the problem?**

Try running `guild.members.get(UID HERE).user.createMessage('abc')` and we get: `Cannot read property 'getDMChannel' of undefined at ExtendedUser.getDMChannel` (in User.js). I'm still trying to figure out what exactly is going on here.

**Comment by KingDGrizzle** [comment]
For me, it seems like when you pass .user it doesn't exist for the bot,as such, it errors. Yet again, not doing .user probably also errors.

**Comment by HilbertGilbertson** [comment]
As clearly stated above, there is no error with [memberobject].user - it returns a valid user object for the member. Nor is the createMessage method undefined. The problem is in createMessage not working on a user object retrieved through a member object.

**Comment by HilbertGilbertson** [comment]
Works after passing user object through Member.js normally, rather than through a getter. #53
