### ISSUE TITLE
[Request] Reason command should also change the strike message when running /strikes

### ISSUE THREAD

**Issue by KingDGrizzle** [GilbertGobbels/GAwesomeBot#58]
Now, this request can break backward compatibility

Currently, when running `/reason`, it only changes the modlog reason. it should also find the correspondent strike and edit that message, so when running `/strikes @User` you get the same strike message as the modlog reason. 
Probably easy to do, by adding some counter to each strike, or using the modlog id in the strikes, and then making reason edit them both. AGAIN, this can potentially fuck backward compatibility if implemented

**Comment by cryptochrome** [comment]
totally upvoting this

**Comment by HilbertGilbertson** [comment]
Indeed. If strikes were indexed, it would certainly make removal easier; I thought of doing this when implementing individual strike removal. If we do index strikes, I'll have to modify my strike removal PR.

The *alternative* solution would be to look for the first strike with the same reason string as the modlog reason and then alter both.  Still, the best solution would seem to be indexing the strikes and adding the strike ID to the modlog record.

**Comment by KingDGrizzle** [comment]
You think you can use the modlog id, then the old reason text and find the strike, then edit that aswell?

**Comment by HilbertGilbertson** [comment]
I already have code to do that, yep. Something along the lines of:

```javascript
// try to find corresponding strike and edit the reason there too
				const modlogDoc = serverDocument.modlog.entries.id(args[0]);
				if(modlogDoc.type == "Warning"){
					const memberDoc = serverDocument.members.id(modlogDoc.affected_user.substring(modlogDoc.affected_user.lastIndexOf('<')).match(/\d+/)[0]);
					if(memberDoc && memberDoc.strikes.length > 0){
						let i = 0;
						const matches = [];
						memberDoc.strikes.map(strike => {
							if(strike.reason == modlogDoc.reason && strike._id == modlogDoc.creator.substring(modlogDoc.creator.lastIndexOf('<')).match(/\d+/)[0]){
									strike.sid = i;
									matches.push(strike);
								}
								i++;
						});
						// check timestamp on all matches to find the nearest strike
						if(matches.length > 0){
							const lowest = null;
							const strikeIndex = null;
							matches.map(strike => {
								let diff = moment(matches[i]).diff(modlogDoc.timestamp);
								if ((strikeIndex === null || diff < lowest) && (!(diff > 10000) && !(diff < -10000))){
									strikeIndex = strike.sid;
								}
							});
							if(!isNaN(strikeIndex)){
								const strikeDoc = memberDoc.strikes;
								strikeDoc[strikeIndex].reason = suffix.substring(suffix.indexOf(" ") + 1).trim();
								memberDoc.strikes = strikeDoc;

							}
						}
					}
				}
```

However, I've not done anything more with `reason` because of the bug with the modlog case IDs. That needs to be fixed first, and by resolving the cause of that problem.

**Comment by KingDGrizzle** [comment]
Let me guess. Counter not going up? 

_this is where my code works with adding 1 and removing 1_

**Comment by HilbertGilbertson** [comment]
> this is where my code works with adding 1 and removing 1

> That needs to be fixed first, and by **resolving the _cause_** of that problem.

**Comment by KingDGrizzle** [comment]
> And since we figured out and fixed the cause of the modlog issues
We can do it now, right?

**Comment by vladfrangu** [comment]
Hey @HilbertGilbertson, don't all mongoose documents have an _id?

**Comment by vladfrangu** [comment]
Thanks to the modularity of mongoose, (yes, that might not be a word or is very wrongly written), and with some slight changes to ModLogs, we'll be able to set strikes that have the same ID as modlog entries. This should allow us to easily do this.

**Comment by vladfrangu** [comment]
Will be handled for any new post-rewrite strikes (if the end-user have enabled the modlog before striking)
