### ISSUE TITLE
[Request] make mute command server-wide

### ISSUE THREAD

**Issue by cryptochrome** [GilbertGobbels/GAwesomeBot#59]
Currently (if I understand correctly), the mute command will only mute the user in the current channel. I would like to be able to mute a user in all channels at once. As an idea on how to do this, take a look at NadekoBot. They simply create a mute role, which is automatically added to all channels, with permission to post denied. Then, when a user is muted using the mute command, the user will just be added to the mute role.

**Comment by KingDGrizzle** [comment]
Possibly doable with an extension. But seems like a good suggestion

**Comment by HilbertGilbertson** [comment]
> Possibly doable with an extension.

**Easily** doable with an extension.

1) Create a mute role with send permissions globally disabled.
2) Add an extension with a short simple command e.g. `gmute` (global mute) and code something like:

```
var roleID = 'ROLE ID HERE';
if (typeof message.mentions != "undefined" && message.mentions != null && message.mentions.length > 0) {
var usrroles = message.mentions[0].roles;
var exist = usrroles.indexOf(roleID);
if(exist > -1) { usrroles.splice(exist, 1); }
  else { usrroles.push(roleID); }
message.mentions[0].edit({ roles: usrroles });
} else { channel.createMessage(message.author.mention + " please specify a user to mute!"); }
```

Substitute `ROLE ID HERE` with the ID of the mute role you have created, and ensure the command is only enabled to be run by Bot Admins of whatever level you wish. Then a Bot Admin need only run `gmute @user` to add a user to the mute role and thus mute them globally. Running the command on a user who already has that role will remove them from it.  Of course, any mod/admin with the power to manage roles would be able to do this without a command, anyway.

**Comment by cryptochrome** [comment]
ok, but would it contribute to modlog in that case (when done through an extension)? That would be key, I think.

**Comment by HilbertGilbertson** [comment]
No, that wouldn't contribute to the modlog. It is possible for extensions to post messages in a specific channel, so an extension could post in the channel with the mod logs.  But in order to add or edit the modlog from within an extension, modifications would need to be made to the extensions API to support this. If it's just a case of needing a log of the action taken, without it having a case ID and amendable reason, then an extensions will allow this. But if you'd want full modlog compatibility, a new command (source, not an extension) would have to be written.

**Comment by cryptochrome** [comment]
I want full modlog compatibility :-)   actually all I care for is that the existing mute command would allow for a global mute (as an option) vs just having a single channel muted.

**Comment by HilbertGilbertson** [comment]
If we were to modify the existing mute command to support such an option (e.g. `mute @user all|reason`), then it would not use a role but create individual mute permissions in _each_ channel. If anyone wants to modify the mute command to do this, they are free to submit a PR; we'll certainly review it.

**Comment by KingDGrizzle** [comment]
Maybe we should include modlog in extensions, but that again can be "ground-breaking". Right now modlog takes specific variables for the type. Inserting custom tags _should_ be doable, but i don't know how easely.

**Comment by HilbertGilbertson** [comment]
@cryptochrome. Create a muted role and set up channel perms so the role cannot send messages in any channel. Then try this:

```javascript
const mutedrole = 'ROLE ID HERE';
const suffix = commandSuffix.split("|");
if(suffix[1] === undefined) suffix[1] = "did something naughty";
if (typeof message.mentions != "undefined" && message.mentions != null && message.mentions.length > 0) {
  if(message.mentions[0].roles.indexOf(mutedrole) > -1) {
    message.mentions[0].removeRole(mutedrole);
    channel.createMessage(message.mentions[0].username + " was already global-muted so I removed them from the role.");
  }
  else {
    const adminmsg = message.mentions[0].mention + " " + suffix[1] + " and was global-muted by " + bot.getMemberName(message.author.id);
    const usermsg = "You" + suffix[1] + " and were added to the role `" + guild.roles.get(mutedrole).name + "`. You may no longer send messages on the " + guild.name + " server.";
    const logreason = suffix[1] + " (GMuted)";
    bot.handleViolation(channel.id, message.mentions[0].id, usermsg, adminmsg, logreason, 'none', mutedrole);
  }
} else {
  channel.createMessage(message.author.mention + " please specify a user to global-mute!");
}
```

That extension will add the user to the muted role and create a modlog incident.

**Comment by cryptochrome** [comment]
This is awesome, thank you!
