### ISSUE TITLE
Broken Auto-Admin-Assign

### ISSUE THREAD

**Issue by GilbertGobbels** [GilbertGobbels/GAwesomeBot#66]
We've all been there;
You invite GAB into your server, and notice you can't access the admin panel for some reason, even though you're the server owner!
A few moments later, your server is complete chaos because a member with the role `Trusted` found out that only they can access the admin panel. Woops.

The Auto Assigning of Admin roles upon creating a server config for the first time is horribly, horribly broken. And can cause a ton of issues. Sometimes, staff is completely locked out, and requires the bot maintainer to either join their server and access their config, or edit the DB directly. Annoying as all.

We need to give the Auto Assigning a good look, and hit it a few times with a stick, because it's been really bad. Really, really bad.

**Comment by KingDGrizzle** [comment]
I'm pretty sure its this code block that just breaks
`// Default admin roles
	const rolesOfOwner = svr.members.get(svr.ownerID).roles.sort((a, b) => {
		return svr.roles.get(a).position - svr.roles.get(b).position;
	});
	if(rolesOfOwner[0] && svr.roles.get(rolesOfOwner[0]).name!="@everyone") {
		serverDocument.config.admins.push({
			_id: rolesOfOwner[0],
			level: 3
		});
	}`

**Comment by GilbertGobbels** [comment]
It just gets the owner's roles. At least, it's supposed to. It doesn't seem to always do this. We should be using a better system anyways. I think we should go off of the ManageServer perm because those people can add GAB to a guild.

**Comment by KingDGrizzle** [comment]
`svr.roles.forEach(role => {
		if(role.name!="@everyone" && !role.managed && role.permissions.has("manageGuild") && !serverDocument.config.admins.id(role.id)) {
			serverDocument.config.admins.push({
				_id: role.id,
				level: 3
			});
		}
	});` 
If we keep this, we _should_ only make manageGuild have admin level 3 at first, then people can add other roles

**Comment by HilbertGilbertson** [comment]
As far as I was aware, and as I've written in the Config guide (work in progress):

> By default, any role that has the "Manage Server" permission will be designated as bot admin level 3, and all of its users will be able to access the Admin Console... The server owner will always be a level 3 bot admin, regardless of whether they have a role with the "Manage Server" permission.

Having doubled checked, it seems this is correct. Although the rolesOfOwner portion seems to be a problem with assigning other roles admin access. I agree the second portion of the code, assigning level 3 to those with manage server permission.

As for the admin of the server not being able to access, I'm not sure of the cause here. The owner of a server can, and should be able to, access the admin console regardless of whether they have a specific role. If I transfer ownership of a server to another user, they are able to login to the admin console although they don't have any special role (just tested this again, works fine).

**Comment by KingDGrizzle** [comment]
Still I think the best way to handle this is:

- when the bot joins, check the guild owner id, give him level 3 (which would work completely different I think)

- Go through all roles, if they have manageGuild or Administrator, give those level 3

- possibly finish the bot.messageBotAdmins

**Comment by HilbertGilbertson** [comment]
> when the bot joins, check the guild owner id, give him level 3 (which would work completely different I think)

This would be a problem, as levels are assigned to roles not to users, and this does not actually involve finding and resolving the real cause of any problem. The owner should be recognised implicitly. WebServer.js uses bot.getUserBotAdmin to determine if a user is a bot admin for each server the bot is on, and of which they are a member.

In bot.getUserBotAdmin, we have:

```
if(svr.ownerID==member.id) {
			return 3;
		}
```

So the question is why this isn't working in some circumstances.

**Comment by ItsLachy** [comment]
For simple MongoDB editing, I use https://github.com/mrvautin/adminMongo.
![image](https://cloud.githubusercontent.com/assets/12377099/22769692/5754f4b2-ee58-11e6-90be-4c3545fe7035.png)

**Comment by GilbertGobbels** [comment]
Fixed in dev branch
