### ISSUE TITLE
<p> tags appearing under server description

### ISSUE THREAD

**Issue by KingDGrizzle** [GilbertGobbels/GAwesomeBot#69]
What I mean is this:

You add the bot to your server, maybe you go to public data and add some info. Thing is, it seems like some things just aren't fully completed. Image [here](http://i.kingdgrizzle.tk/2017/02/G0o7S4.png)

**Comment by KingDGrizzle** [comment]
<em> replaced the `-`

**Comment by GilbertGobbels** [comment]
Issue is already known, so is solution. Will fix in later commit.
