### ISSUE TITLE
[Bug] mentions not working in extensions

### ISSUE THREAD

**Issue by HilbertGilbertson** [GilbertGobbels/GAwesomeBot#7]
When trying to use message.mentions within an extension, nothing happens. No error is produced in the logs to indicate the object is undefined. But it would appear to be completely empty.

To reproduce:
`channel.createMessage(message.mentions.length)`
Run the extension, mentioning as many or as few users as you wish.

Result: nothing, not even 0. No errors occur, nor is any message produced. 

As for roleMentions, only role IDs are returned when mentioning a guild role (rather than the object for that role). Evidently something has been left unfinished. In Modules/ExtensionStructures/Message.js:
`class Message {
	// TODO:
// 1. roleMentions should be Array(Role) instead? (Not how eris works tho)
...`

**Comment by GilbertGobbels** [comment]
Both roleMentions and mentions aren't working even when they are taken directly from the eris.js object. However, other commands using the mentions object directly from eris are working fine. Might require some deeper digging, but I'm pretty clueless at this point.

**Comment by HilbertGilbertson** [comment]
Okay, so when a guild role is mentioned, roleMentions returns only IDs of said roles (in an array) but not an array of role objects. As it stands, mentions is broken as reported.

If we get rid of:
`this.mentions = () => {
			const Collection = require("./Collection");
			const User = require("./User");

			const mentions = new Collection(User);
			mentions.forEach(user => {
				this.mentions.add(new User(user));
			});
			return mentions;
		};` and replace it simply with `this.mentions = erisMessage.mentions;` (or place this line after the above) then mentions works; returning an array of users with their id, bot, avatar, username and discriminator keys.

It seems it was intended that, within an extension, message.mentions would return an array of User objects (with additional information like avatarURL) instead of the more limited information in msg.mentions. This makes sense given that extensions don't have the same degree of access to information as other code. But the code (cited above) is not working properly - it doesn't even result in an empty array, instead passing nothing back to the extension.

If this is to be fixed (rather than removed, and I think that would be a much better idea), might I suggest using the Member (in Member.js) object rather than the User object anyway, as it contains much more information, as well as functions like addRole(), ban(), etc.

**Comment by KingDGrizzle** [comment]
Worst case, we'll have to do it like in v3, `<@ + message.author.id + >`

**Comment by HilbertGilbertson** [comment]
Mentions, not mention! i.e. !cmd @user @user2 @user3 - message.mentions would be an array of the mentioned users' User objects.  Also, in v3 you could do message.author.mention!

**Comment by KingDGrizzle** [comment]
Oh.. Then, we'll just have to wait or attempt to fix it and PR :D

**Comment by HilbertGilbertson** [comment]
> Oh.. Then, we'll just have to wait or attempt to fix it and PR :D

Oddly enough I'd figured that much out all by myself! ;)

**Comment by KingDGrizzle** [comment]
But would your fix apply to all ranks, users and channels? (Pretty sure thats all you can mention)

**Comment by HilbertGilbertson** [comment]
#33 Patched mentions.

message.roleMentions remains a simple array of role IDs (rather than Role objects), but this issue is relatively minor in comparison to the (now resolved) problem in message.mentions.
