### ISSUE TITLE
[bug] giveaway won't accept any time other than '.' (default of 1 hour)

### ISSUE THREAD

**Issue by HilbertGilbertson** [GilbertGobbels/GAwesomeBot#70]
<img width="650" alt="bug" src="https://cloud.githubusercontent.com/assets/24899023/22834164/2da0f0b2-efac-11e6-84eb-58312c6cf546.png">

Milliseconds or plain language, neither matters. Only `.` is accepted.

**Comment by HilbertGilbertson** [comment]
This issue in itself is easily fixed by changing `parseDuration(message)` to `parseDuration(message.content)` in line 137 of PM/giveaway.js.

However, fixing this only reveals deeper problems with giveaways not ending properly. The database is updated with the correct end time as specified (as well as correct secret information etc) but at the point of expiry, no winner is announced. The giveaway does close correctly at the end of the time period (with 'isOngoing' changing back to false), but no announcement, winner, or secret information PM'd to the winner.

**Comment by KingDGrizzle** [comment]
That can probably be a problem on (in case of the dev branch) my side. If you could fix it, and I'll look into the messages, that would be awesome
