### ISSUE TITLE
[BUG] Bot sends MOTD everytime bot restarts

### ISSUE THREAD

**Issue by JjTheHusky** [GilbertGobbels/GAwesomeBot#75]
Hi, this seems like a pretty natural bug, but it can be very annoying if the bot often crashes and auto restarts

What occurs is while the bot does send the MOTD every X amount of time, however if the bot stops/crashes, and is auto restarted, for instance with PM2, it will send the MOTD again, probably also resetting the timer.

[Such as in this picture](https://img.cdn.hesky.co/t4zM8-02-11-17.png) The first one is when I first added the MOTD. normal
The second was when I restarted the bot, not normal :P

**Comment by GilbertGobbels** [comment]
Yep, this is defo a problem.
This also includes timer extensions, because the bot's code sets the MOTD/timer setTimeout() function on startup.

While this is annoying, it's most likely better to prevent crashes from the bot all together. Besides, possibly a save shutdown command? Where the bot dumps it's session data (such as timer-times) in a temp file, and reads that file upon boot.

**Comment by HilbertGilbertson** [comment]
> possibly a save shutdown command? Where the bot dumps it's session data (such as timer-times) in a temp file, and reads that file upon boot.

Sounds like a a good idea. Should it be a file or stored in the DB? _remembers the days of ABv3 and oversized JSON files_

**Comment by GilbertGobbels** [comment]
I was thinking about a /tmp/ dir

**Comment by HilbertGilbertson** [comment]
I see. Containing json files? e.g. tmp/timers.json etc? Nice.

**Comment by KingDGrizzle** [comment]
Orr use the same way as giveaways, where the setTimeout does the MOTD after x time, saving the time in the db?

**Comment by theanidox** [comment]
Something could be stored in the DB, maybe on shutdown set it to a certain value that the bot reads while starting up, telling it whether to say the MOTD

**Comment by Gilbert142** [comment]
Fixed in #184
