### ISSUE TITLE
[BUG] bufferUtil error when accessing admin console.

### ISSUE THREAD

**Issue by genzzii** [GilbertGobbels/GAwesomeBot#81]
OS: Arch Linux
Branch: master and development
node version: 6.2.2, 6.9.5, 7.5.0
socket.io version: 1.4.8, 1.7.2

Bot runs normally until I tried to change any options like command options from the admin console.
The same error instantly happened without opening or refreshing the admin console page when restarting the bot.

```node.js
/home/lealith/GAwesomeBot/node_modules/engine.io/node_modules/ws/lib/Receiver.js:306
  if (mask != null && buf != null) bufferUtil.unmask(buf, mask);
                                             ^

TypeError: Cannot read property 'unmask' of undefined
    at Receiver.unmask (/home/lealith/GAwesomeBot/node_modules/engine.io/node_modules/ws/lib/Receiver.js:306:46)
    at Receiver.finish (/home/lealith/GAwesomeBot/node_modules/engine.io/node_modules/ws/lib/Receiver.js:505:25)
    at Receiver.expectHandler (/home/lealith/GAwesomeBot/node_modules/engine.io/node_modules/ws/lib/Receiver.js:493:33)
    at Receiver.add (/home/lealith/GAwesomeBot/node_modules/engine.io/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (/home/lealith/GAwesomeBot/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```

**Comment by KingDGrizzle** [comment]
From what I've heard, your using the master branch. Can you try switching to the development branch and try again? (Which also means you'll have to re-build your DB and config.json)

**Comment by medmedmeddia** [comment]
I'm experiencing this as well. I tried switching to the development branch but I the same thing happened :/

OS: Debian 8
Node Version: 7.5.0
Socket.io Version: 4.1.2

**Comment by genzzii** [comment]
Just now I tried using the latest development branch, still having issue.

@medmedmeddia err, did you mistype your socket.io version? I'm pretty sure the latest one is 1.7.2

**Comment by medmedmeddia** [comment]
whoops, my bad @genzzii . i fixed it.

**Comment by KingDGrizzle** [comment]
Right, from what it seems, it _might_ be a OS-based issue. I'll test the systems localy and see if thats the case and let you know, ok?

**Comment by KingDGrizzle** [comment]
Interesting.. On my side, I can't even start the bot due to BufferUtils of Eris. Will see about a possible fix

**Comment by KingDGrizzle** [comment]
Right, this might sound dumb, but:

Can you go to node_modules/engine.io/node_modules/ws and run `npm install`

**Comment by GilbertGobbels** [comment]
That does sound a little dumb...
When running `npm install` npm checks all your dependencies (here engine.io) and installs THEIR dependencies aswell.

So really, when you run `npm install` while being in GAB's root folder npm already automaticly runs `npm install` in all the node_modules's folders (in a way, not exactly, but just to give you the idea)

**Comment by KingDGrizzle** [comment]
Except that, it didn't apply on my local debian 8 VM. I don't know if node knows how to handle modules outside of the folder. Aka, if the requirement for engine.io is bufferUtils, it won't find outside the folder. So, each  module needs its own node_modules.

Yes, it sounds dumb, but what if it works? We gonna test it before, right?

**Comment by genzzii** [comment]
Actually it's working, I tried it and the bot no longer crashed when accessing the admin console.
I searched similar issues like this and seems like there's a [bug ](http://stackoverflow.com/questions/18401606/npm-doesnt-install-module-dependencies)where npm doesn't install all of it's modules dependencies.

**Comment by GilbertGobbels** [comment]
Hm-hm, npm is not behaving as expected in that case. A third-party issue, then.
