### ISSUE TITLE
[Bug] [development] userDocument not auto-created on member join

### ISSUE THREAD

**Issue by KingDGrizzle** [GilbertGobbels/GAwesomeBot#83]
Really can't explain it using the tile, so I'll do it here.

Basically, you got a new-comer on your server. Checking his strikes would yield a "Something went wrong", This is most likely due to the strikes array not being initialised. (I think)

Striking and then removing fixes that issue

**Comment by HilbertGilbertson** [comment]
So it seems that on the dev branch, new server members do not immediately appear in the DB, so when `strikes` is run, an error occurs as a result of a non-existent strikes array for a user not in the DB.  This problem does not seem to occur with the GAB instance. Perhaps @GilbertGobbels has an idea of what is going on?! *scratches head*

**Comment by GilbertGobbels** [comment]
@HilbertGilbertson Yeah, I do;
GuildUserAdded.js does not store a new user object on purpose, as all modules call `db.users.findOrCreate()` when they need to fetch a user object. If a module doesn't call this function, but instead only tries to look a user object up (without having a fallback for when it doesn't exist.) it breaks.

**Comment by KingDGrizzle** [comment]
Which I fixed in the PR you marked invalid 😛. Strikes was probably the only command which expected the strikes array to be already existant, instead of testing it, which is shown in a compared-view between master and dev branch.

```javascript
const info = (targetMemberDocument ? targetMemberDocument.strikes : []).map(strikeDocument => {
				const creator = msg.guild.members.get(strikeDocument._id);
				return `${strikeDocument.reason} - ${moment(strikeDocument.timestamp).fromNow()} from @${creator ? bot.getName(msg.guild, serverDocument, creator) : "invalid-user"}`;
			});```

This check wasn't made in the dev-branch. And I fixed that

**Comment by GilbertGobbels** [comment]
Fixed on dev branch
