### ISSUE TITLE
[Bug] Tags don't respect the admin-only setting

### ISSUE THREAD

**Issue by KingDGrizzle** [GilbertGobbels/GAwesomeBot#88]
Having found out on Aurora Community about the ability for anyone to run `/tag name | test`, even with the option in the admin console being Admin-only.

This might be just a slight overlook, hence the needs confirmation label

**Comment by KingDGrizzle** [comment]
@GilbertGobbels got any clues?

**Comment by KingDGrizzle** [comment]
Might have found out the issue, will PR soon

**Comment by vladfrangu** [comment]
@GilbertGobbels This is done, correct?

**Comment by Gilbert142** [comment]
Fixed in commit 423049a
