### ISSUE TITLE
[Bug] Ranking up spams the DM's of the user

### ISSUE THREAD

**Issue by KingDGrizzle** [GilbertGobbels/GAwesomeBot#90]
_needs confirmation_

Seems like for some people, ranking up will just spam their DM's.

Can't tell why, but help would be nice, @HilbertGilbertson maybe you can check it out?

**Comment by kortakai** [comment]
I can confirm this happens on our servers. We don't use DM for that so it's fun watching our chat flood out with rank up notifications

**Comment by KingDGrizzle** [comment]
This might of had a issue with Eris deprecating msg.guild and wanting to use msg.channel.guild.

What bot are you using, and can you test it again _in case of AuroraBot or HuskyBot_

**Comment by KingDGrizzle** [comment]
We need confirmation that this issue still happens, otherwise it'll be marked as solved / wontfix

**Comment by KingDGrizzle** [comment]
This probably was caused by Eris deprecating, so I'll mark as closed. Make a new issue if still present, with reproduction steps if available
