### ISSUE TITLE
[Request] Alias msg to message in Extensions

### ISSUE THREAD

**Issue by KingDGrizzle** [GilbertGobbels/GAwesomeBot#92]
As you know, `message` is what you have to use in order to get the message content.

_Have I not tried msg before, with a catastrophic failure, this wouldn't have been it_
 It would be nice if we can have `msg`, as we are very used to it, its faster to type, and has the same properties

**Comment by HilbertGilbertson** [comment]
There are **numerous** differences between elements of the Eris API and the extensions API, so it will always be necessary for those writing extensions to familiarise themselves with the Extensions API. `msg` not working incidentally serves as an important reminder to those working with extensions that the extensions API and Eris API are similar but **not the same**. Helpfully, _someone_ 😉 has written it all down to make the API easier to understand, both for those new to Eris, and for those familiar with it.

As someone whose primary focus is on extensions (and who has 6000 lines of AB3 extension code to rewrite for GAB), I don't see the need for this. Personally, I would consider this an unnecessary _wontfix_, but I appreciate that others may have differing views on the matter.

**Comment by KingDGrizzle** [comment]
Closing this, if people really want to do this, `let msg = message`
