### ISSUE TITLE
[Request / Idea] Switch to Google Translate

### ISSUE THREAD

**Issue by KingDGrizzle** [GilbertGobbels/GAwesomeBot#96]
As Microsoft's Translator API requires a subscription (be it free) on portal.azure.com (which asks you for a credit card to verify your a human), Google seems like another decent solution, its very easy to make API keys and set them up,

Needs people's feedback

**Comment by HilbertGilbertson** [comment]
Google does not offer the official translate API unless you pay. Is a credit (or also presumably debit) card that problematic?

**Comment by KingDGrizzle** [comment]
Apparently, Microsoft Translation is also paid.

We should find an API thats: 1. Easy to setup 2. Available

**Comment by HilbertGilbertson** [comment]
a) I'm using it with GAB.
b) The Azure website clearly shows the free plan

<img width="471" alt="screen shot 2017-03-10 at 20 31 57" src="https://cloud.githubusercontent.com/assets/24899023/23812031/a4521490-05d0-11e7-9fbe-e1a8e9e7babd.png">

**Comment by KingDGrizzle** [comment]
Yes, but you need a credit card to verify. That your human. Which some people might not want to give or don't have. 

Anyways, close this if you want

**Comment by HilbertGilbertson** [comment]
With such services proving you are a human is not atypical.  If you use Google, you need a Google account - which in most cases requires SMS verification. One might not wish to provide their phone number; but that's required with the solution you are suggesting. And I assume you actually mean credit or _debit_ card. Even children can have debit cards (at least in the UK, the minimum age is 11).

I'm happy to keep it open for other's feedback. The fact that I'm not convinced doesn't mean others' views don't matter ;)

**Comment by HilbertGilbertson** [comment]
Okay, scratch my earlier comments. Having looked into this, the API **must** be replaced.

The current translation API uses Microsoft DataMarket, which is being [retired](https://datamarket.azure.com/dataset/bing/microsofttranslator) on 31st March. Old keys will thus stop working. New keys, with Microsoft Cognitive Services API, absolutely **can** be created with Microsoft for **free** (although a debit/credit card and SMS verification are needed) - with _exactly_ the same limitations as before (the free package with up to 2 million chars per month). However, these new keys won't currently work with GAB as the translate command uses [bing-translate](https://www.npmjs.com/package/bing-translate); last updated 2 years ago.

Instead we need to switch to something like [mstranslator](https://www.npmjs.com/package/mstranslator), which uses the Cognitive Services API.

Or the alternative is to switch to an entirely different API.
