### ISSUE TITLE
[Request/Idea] Allow where Chatterbot can be used in selected channels.

### ISSUE THREAD

**Issue by JjTheHusky** [GilbertGobbels/GAwesomeBot#98]
Like how you can select whether a command can be ran in a specific channel, I think that chatterbot should be added to that list, instead of it being server wide.

**Comment by theanidox** [comment]
I'd use this (have chatterbot off in every channel except `#botcommands`).
It'd reduce spam of people using the chatterbot in main chat

**Comment by vladfrangu** [comment]
d3d6bc70ef1d25d5eec35d981e31a251afc08cf3 🎉
